name: openweather_app
description: An open weather app

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.4.4
  http: ^1.1.0
  intl: ^0.18.1
  go_router: ^12.1.1

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1
  network_image_mock: ^2.1.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
